In [44]:

# code using line search-- newton method
import numpy as np
obj = lambda x: (2-2*x[0]-3*x[1])**2 + x[0]**2 +(x[1]-1)**2 # defining the given function 
def grad(x):
     return np.array([10*x[0]+12*x[1]-8, 20*x[1]+12*x[0]-14]) #returning the giving defined gradient of the function 
eps = 1e-3  #  its an termination criterion  
x0= np.zeros((2),dtype=int)  # initial guess
k = 0  # counter
soln = [x0]  # using this array which helps to store the error  
x = soln[k]  # initial guess
error = np.linalg.norm(grad(x))  #this will compute the error 
a = 1  # we have set an fixed part to start this as one 

# Armijo line search
def line_search(x):
    a = 1.  # initialize step size
    h=([[10,12],[12,20]])
    d=-np.matmul(np.linalg.inv(h),grad(x))
    def phi(a,x):
        return obj(x)+a*0.8*np.dot(grad(x),d)
   
#     phi = lambda a, x: obj(x) + a*0.8*np.dot(grad(x),d)  # define phi as a search criterion
    while phi(a,x)<obj(x+a*d):  # while phi(a,x)<obj(x-a*grad(x)): # if f(x+a*d)>phi(a) then backtrack. d is the search direction
        a = 0.5*a
    return a

while error >= eps:  # keep searching while gradient norm is larger than eps
    a = line_search(x)
    h=([[10,12],[12,20]])
    d=-np.matmul(np.linalg.inv(h),grad(x))
    x = x+a*d
    soln.append(x)
    error = np.linalg.norm(grad(x))
   
soln  # print the solution

[array([0, 0]),
 array([-0.03571429,  0.19642857]),
 array([-0.0625 ,  0.34375]),
 array([-0.08258929,  0.45424107]),
 array([-0.09765625,  0.53710938]),
 array([-0.10895647,  0.5992606 ]),
 array([-0.11743164,  0.64587402]),
 array([-0.12378802,  0.68083409]),
 array([-0.1285553 ,  0.70705414]),
 array([-0.13213076,  0.72671918]),
 array([-0.13481236,  0.74146795]),
 array([-0.13682355,  0.75252954]),
 array([-0.13833195,  0.76082572]),
 array([-0.13946325,  0.76704786]),
 array([-0.14031172,  0.77171447]),
 array([-0.14094808,  0.77521442]),
 array([-0.14142534,  0.77783939]),
 array([-0.14178329,  0.77980811]),
 array([-0.14205176,  0.78128466]),
 array([-0.1422531 ,  0.78239206]),
 array([-0.14240411,  0.78322262]),
 array([-0.14251737,  0.78384554]),
 array([-0.14260231,  0.78431272]),
 array([-0.14266602,  0.78466311]),
 array([-0.1427138 ,  0.78492591]),
 array([-0.14274964,  0.785123  ]),
 array([-0.14277651,  0.78527082]),
 array([-0.14279667,  0.78538169]),
 array([-0.1428117

[img1](images/0001.jpg)
[img2](images/0002.jpg)
[img3](images/0003.jpg)
[img4](images/0004.jpg)
[img5](images/0005.jpg)
[img6](images/0006.jpg)
[img7](images/0007.jpg)
[img8](images/0008.jpg)
[img9](images/0009.jpg)
[img10](images/0010.jpg)
[img11](images/0011.jpg)
[img12](images/0012.jpg)
[img13](images/0013.jpg)
[img14](images/0014.jpg)
